--- 
id: proxycontract
name: The Whys and Hows of the Proxy Contract
summary: This tutorial gives a short introduction of the web3.js library, querying the block number
level: 4
tags: 
  - Remix
  - Solidity
  - Code Patterns